[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXTAUTH_URL = "https://nirvanadespang.netlify.app"

  NEXT_PUBLIC_SUPABASE_URL = ""
  NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
  SUPABASE_SERVICE_ROLE_KEY = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"
