[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXTAUTH_URL = "https://nirvanadespa.ng.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"
